title: Sunil Sarolkar
email: spsarolkar@gmail.com
<<<<<<< HEAD
description: > # this means to ignore newlines until "baseurl:"
  Sunil Sarolkar Profile Page
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://spsarolkar.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll
=======
description: > 
  Software Engineer | AI Explorer | 14+ Years of Java & ML Experience

baseurl: "" # Leave this empty if deploying to GitHub Pages root
url: "https://spsarolkar.github.io" # Update with your GitHub Pages URL

author:
  name: "Sunil Sarolkar"
  email: "spsarolkar@gmail.com"

twitter_username: sunilsarolkar
github_username: spsarolkar
>>>>>>> gh-pages

# Build settings
markdown: kramdown
theme: minima
highlighter: rouge
timezone: Asia/Kolkata

plugins:
  - jekyll-feed
  - jekyll-seo-tag

<<<<<<< HEAD
timezone: Asia/Kolkata

future: true
=======
social_links:
  github: spsarolkar
  linkedin: sunil-sarolkar-451b2023
  email: spsarolkar@gmail.com

future: true

# Markdown Rendering Settings
kramdown:
  input: GFM
  syntax_highlighter: redcarpet
  syntax_highlighter_opts:
    css_class: 'highlight'
    span:
      line_numbers: false
    block:
      line_numbers: true

# Optional: Extensions for redcarpet if ever used
redcarpet:
  extensions: 
    - fenced_code_blocks
    - no_intra_emphasis
    - tables
    - autolink
    - strikethrough
    - with_toc_data
>>>>>>> gh-pages

redcarpet:
    extensions: ["fenced_code_blocks","no_intra_emphasis", "tables", "autolink", "strikethrough", "with_toc_data"]

<<<<<<< HEAD
repository  : spsarolkar/spsarolkar.github.io
comments:
  provider  : "staticman_v2"
staticman:
  branch    : "master"

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
=======
# Exclude files from build
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/
>>>>>>> gh-pages
