title: Sunil Sarolkar
email: spsarolkar@gmail.com
description: > 
  Software Engineer | AI Explorer | 14+ Years of Java & ML Experience

baseurl: "" # Leave this empty if deploying to GitHub Pages root
url: "https://spsarolkar.github.io" # Update with your GitHub Pages URL

author:
  name: "Sunil Sarolkar"
  email: "spsarolkar@gmail.com"

twitter_username: sunilsarolkar
github_username: spsarolkar

# Build settings
markdown: kramdown
theme: minima
highlighter: rouge
timezone: Asia/Kolkata

plugins:
  - jekyll-feed
  - jekyll-seo-tag

social_links:
  github: spsarolkar
  linkedin: sunil-sarolkar-451b2023
  email: spsarolkar@gmail.com

future: true

# Markdown Rendering Settings
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'
    span:
      line_numbers: false
    block:
      line_numbers: true

# Optional: Extensions for redcarpet if ever used
redcarpet:
  extensions: 
    - fenced_code_blocks
    - no_intra_emphasis
    - tables
    - autolink
    - strikethrough
    - with_toc_data

# Exclude files from build
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/
